### PR TITLE
Use action button to switch polling

### PR DESCRIPTION
**Pull request by upsuper**
This makes it possible to toggle polling without opening the addon management page.

When I am not landing patches, I do not want to track the current tree status, thus I hope not to keep querying the server about the status.

### CODE REVIEW

**Comment by jsantell** [comment]
Thanks for the PR! You're right, sometimes I want to have an awareness of if a tree is up, but sometimes I would rather turn it off. Thoughts on how to get to the status page that's there via click though? Is that page even useful for this use case?

**Comment by upsuper** [comment]
Well, personally, I don't usually care much about the status page. Given the addon has shown the reason in tooltip, I suppose the status page doesn't provide more information.

Also, I think that, opening any website is much eaiser and quicker than switching an addon thanks to url autocompletion, which makes me wonder do we really need another shortcut for opening that page?

If you really want to open status page from that button, as well as this function, I guess we probably should add a popup menu or a panel to that button. But that would need a lot more change :(

**Comment by upsuper** [comment]
Ping. Any thoughts about my last comment?

**Comment by jsantell** [comment]
Gonna land this and try it out a bit, got some feedback and most people only use the tooltip status, and not the full page anyway :) Thanks!!

**Comment by upsuper** [comment]
Are you going to release a new version with this change?

**Comment by theres-waldo** [comment]
> Well, personally, I don't usually care much about the status page. Given the addon has shown the reason in tooltip, I suppose the status page doesn't provide more information.

I find the status page useful for seeing how long ago the tree was closed (which gives me a better idea of how soon it might open).

> Also, I think that, opening any website is much eaiser and quicker than switching an addon thanks to url autocompletion, which makes me wonder do we really need another shortcut for opening that page?

Not sure I follow this. To me, clicking a button in the browser UI is quicker than giving focus to the address bar and typing things there.

**Comment by upsuper** [comment]
But turning it on/off is far more inconvenient than opening the status page before. And personally I do the former much more frequently than the latter, because most of the time I'm not interested in monitoring the tree status at all. (Consequently continuing pinging in most of the time is useless and could be considered harmful regarding server pressure and personal privacy.)

(Also I don't really think the time how long the tree has been closed is a good indicator of when it would be opened.)

**Pull request merged**
